{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import matplotlib.pyplot as plt\n",
    "low_memory = False\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Vlad\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  interactivity=interactivity, compiler=compiler, result=result)\n"
     ]
    }
   ],
   "source": [
    "# Connecting to CSVs\n",
    "motive_data = pd.read_csv(\"old_csv/19_Motive.csv\")\n",
    "victim_data = pd.read_csv(\"old_csv/32_Victim.csv\")\n",
    "firearms_data = pd.read_csv(\"old_csv/34_Firearm.csv\")\n",
    "air_data = pd.read_csv(\"old_csv/data.csv\",encoding = \"ISO-8859-1\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cleaning up Air Pollution Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>location</th>\n",
       "      <th>so2</th>\n",
       "      <th>no2</th>\n",
       "      <th>rspm</th>\n",
       "      <th>spm</th>\n",
       "      <th>pm2_5</th>\n",
       "      <th>date</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>state</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>4.8</td>\n",
       "      <td>17.4</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>3.1</td>\n",
       "      <td>7.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>6.2</td>\n",
       "      <td>28.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>6.3</td>\n",
       "      <td>14.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-03-01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>4.7</td>\n",
       "      <td>7.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-03-01</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 location  so2   no2  rspm  spm  pm2_5        date\n",
       "state                                                             \n",
       "Andhra Pradesh  Hyderabad  4.8  17.4   NaN  NaN    NaN  1990-02-01\n",
       "Andhra Pradesh  Hyderabad  3.1   7.0   NaN  NaN    NaN  1990-02-01\n",
       "Andhra Pradesh  Hyderabad  6.2  28.5   NaN  NaN    NaN  1990-02-01\n",
       "Andhra Pradesh  Hyderabad  6.3  14.7   NaN  NaN    NaN  1990-03-01\n",
       "Andhra Pradesh  Hyderabad  4.7   7.5   NaN  NaN    NaN  1990-03-01"
      ]
     },
     "execution_count": 79,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Dropping irrelevant Columns\n",
    "df_air_data = pd.DataFrame(air_data)\n",
    "df_air_data = df_air_data.set_index('state')\n",
    "clean_air_data = df_air_data.drop([\"stn_code\", \"sampling_date\",\"agency\",\"type\",\"location_monitoring_station\"],1)\n",
    "clean_air_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>location</th>\n",
       "      <th>so2</th>\n",
       "      <th>no2</th>\n",
       "      <th>rspm</th>\n",
       "      <th>spm</th>\n",
       "      <th>pm2_5</th>\n",
       "      <th>date</th>\n",
       "      <th>Year</th>\n",
       "      <th>Month</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>state</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>4.8</td>\n",
       "      <td>17.4</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "      <td>1990</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>3.1</td>\n",
       "      <td>7.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "      <td>1990</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>6.2</td>\n",
       "      <td>28.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-02-01</td>\n",
       "      <td>1990</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>6.3</td>\n",
       "      <td>14.7</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-03-01</td>\n",
       "      <td>1990</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>4.7</td>\n",
       "      <td>7.5</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1990-03-01</td>\n",
       "      <td>1990</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 location  so2   no2  rspm  spm  pm2_5        date  Year Month\n",
       "state                                                                         \n",
       "Andhra Pradesh  Hyderabad  4.8  17.4   NaN  NaN    NaN  1990-02-01  1990    01\n",
       "Andhra Pradesh  Hyderabad  3.1   7.0   NaN  NaN    NaN  1990-02-01  1990    01\n",
       "Andhra Pradesh  Hyderabad  6.2  28.5   NaN  NaN    NaN  1990-02-01  1990    01\n",
       "Andhra Pradesh  Hyderabad  6.3  14.7   NaN  NaN    NaN  1990-03-01  1990    01\n",
       "Andhra Pradesh  Hyderabad  4.7   7.5   NaN  NaN    NaN  1990-03-01  1990    01"
      ]
     },
     "execution_count": 80,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Separating Year and Month into Separate columns\n",
    "clean_air_data['Year'] = clean_air_data['date'].str[:4]\n",
    "clean_air_data['Month'] = clean_air_data['date'].str[-2:]\n",
    "clean_air_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>location</th>\n",
       "      <th>so2</th>\n",
       "      <th>no2</th>\n",
       "      <th>rspm</th>\n",
       "      <th>spm</th>\n",
       "      <th>pm2_5</th>\n",
       "      <th>date</th>\n",
       "      <th>Year</th>\n",
       "      <th>Month</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>state</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>14.4</td>\n",
       "      <td>78.3</td>\n",
       "      <td>0.0</td>\n",
       "      <td>291.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2001-01-01</td>\n",
       "      <td>2001</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>15.6</td>\n",
       "      <td>73.6</td>\n",
       "      <td>0.0</td>\n",
       "      <td>340.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2001-02-01</td>\n",
       "      <td>2001</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>14.8</td>\n",
       "      <td>39.8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>189.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2001-03-01</td>\n",
       "      <td>2001</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>13.4</td>\n",
       "      <td>37.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>220.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2001-04-01</td>\n",
       "      <td>2001</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>14.1</td>\n",
       "      <td>30.3</td>\n",
       "      <td>0.0</td>\n",
       "      <td>183.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2001-05-01</td>\n",
       "      <td>2001</td>\n",
       "      <td>01</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 location   so2   no2  rspm    spm  pm2_5       date  Year  \\\n",
       "state                                                                        \n",
       "Andhra Pradesh  Hyderabad  14.4  78.3   0.0  291.0    0.0 2001-01-01  2001   \n",
       "Andhra Pradesh  Hyderabad  15.6  73.6   0.0  340.0    0.0 2001-02-01  2001   \n",
       "Andhra Pradesh  Hyderabad  14.8  39.8   0.0  189.0    0.0 2001-03-01  2001   \n",
       "Andhra Pradesh  Hyderabad  13.4  37.1   0.0  220.0    0.0 2001-04-01  2001   \n",
       "Andhra Pradesh  Hyderabad  14.1  30.3   0.0  183.0    0.0 2001-05-01  2001   \n",
       "\n",
       "               Month  \n",
       "state                 \n",
       "Andhra Pradesh    01  \n",
       "Andhra Pradesh    01  \n",
       "Andhra Pradesh    01  \n",
       "Andhra Pradesh    01  \n",
       "Andhra Pradesh    01  "
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Filtering the data to dates we need\n",
    "clean_air_data[\"date\"]=pd.to_datetime(clean_air_data[\"date\"])\n",
    "dates = (clean_air_data[\"date\"] > \"12-31-2000\") & (clean_air_data[\"date\"] <= \"12-31-2009\")\n",
    "clean_air_data = clean_air_data.loc[dates]\n",
    "\n",
    "# Replacing the NaNs\n",
    "clean_air_data.fillna(0, inplace=True)\n",
    "clean_air_data.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cleaning up Motive Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>CHNAMurder_Cause_By_TerroristExtremist</th>\n",
       "      <th>CHNAMurder_Cause_Casteism</th>\n",
       "      <th>CHNAMurder_Cause_Class_Conflict</th>\n",
       "      <th>CHNAMurder_Cause_Communalism</th>\n",
       "      <th>CHNAMurder_Cause_Dowry</th>\n",
       "      <th>CHNAMurder_Cause_For_Political_reason</th>\n",
       "      <th>CHNAMurder_Cause_Gain</th>\n",
       "      <th>CHNAMurder_Cause_Love_AffairsSexual_Relations</th>\n",
       "      <th>CHNAMurder_Cause_Lunacy</th>\n",
       "      <th>...</th>\n",
       "      <th>Murder_Cause_Dowry</th>\n",
       "      <th>Murder_Cause_For_Political_reason</th>\n",
       "      <th>Murder_Cause_Gain</th>\n",
       "      <th>Murder_Cause_Love_AffairsSexual_Relations</th>\n",
       "      <th>Murder_Cause_Lunacy</th>\n",
       "      <th>Murder_Cause_Other_Causes_or_Motives</th>\n",
       "      <th>Murder_Cause_Personal_Vendetta_or_Enmity</th>\n",
       "      <th>Murder_Cause_Property_Dispute</th>\n",
       "      <th>Murder_Cause_Total</th>\n",
       "      <th>Murder_Cause_Witchcraft</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Odisha</th>\n",
       "      <td>2007</td>\n",
       "      <td>0</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>138</td>\n",
       "      <td>4</td>\n",
       "      <td>60</td>\n",
       "      <td>61</td>\n",
       "      <td>1</td>\n",
       "      <td>755</td>\n",
       "      <td>113</td>\n",
       "      <td>43</td>\n",
       "      <td>1210</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Jharkhand</th>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>3</td>\n",
       "      <td>...</td>\n",
       "      <td>70</td>\n",
       "      <td>25</td>\n",
       "      <td>103</td>\n",
       "      <td>158</td>\n",
       "      <td>3</td>\n",
       "      <td>599</td>\n",
       "      <td>242</td>\n",
       "      <td>228</td>\n",
       "      <td>1488</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Jharkhand</th>\n",
       "      <td>2004</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>3</td>\n",
       "      <td>...</td>\n",
       "      <td>70</td>\n",
       "      <td>25</td>\n",
       "      <td>103</td>\n",
       "      <td>158</td>\n",
       "      <td>3</td>\n",
       "      <td>599</td>\n",
       "      <td>242</td>\n",
       "      <td>228</td>\n",
       "      <td>1488</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bihar</th>\n",
       "      <td>2010</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>47</td>\n",
       "      <td>35</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>168</td>\n",
       "      <td>24</td>\n",
       "      <td>352</td>\n",
       "      <td>187</td>\n",
       "      <td>5</td>\n",
       "      <td>1228</td>\n",
       "      <td>441</td>\n",
       "      <td>916</td>\n",
       "      <td>3362</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Karnataka</th>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>52</td>\n",
       "      <td>6</td>\n",
       "      <td>55</td>\n",
       "      <td>130</td>\n",
       "      <td>0</td>\n",
       "      <td>1093</td>\n",
       "      <td>188</td>\n",
       "      <td>98</td>\n",
       "      <td>1627</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 29 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           Year  CHNAMurder_Cause_By_TerroristExtremist  \\\n",
       "Area_Name                                                 \n",
       "Odisha     2007                                       0   \n",
       "Jharkhand  2002                                       0   \n",
       "Jharkhand  2004                                       0   \n",
       "Bihar      2010                                       0   \n",
       "Karnataka  2002                                       0   \n",
       "\n",
       "           CHNAMurder_Cause_Casteism  CHNAMurder_Cause_Class_Conflict  \\\n",
       "Area_Name                                                               \n",
       "Odisha                            11                                0   \n",
       "Jharkhand                          3                                2   \n",
       "Jharkhand                          3                                2   \n",
       "Bihar                              2                                2   \n",
       "Karnataka                          1                                0   \n",
       "\n",
       "           CHNAMurder_Cause_Communalism  CHNAMurder_Cause_Dowry  \\\n",
       "Area_Name                                                         \n",
       "Odisha                                0                       2   \n",
       "Jharkhand                             2                      13   \n",
       "Jharkhand                             2                      13   \n",
       "Bihar                                 0                      11   \n",
       "Karnataka                             0                       0   \n",
       "\n",
       "           CHNAMurder_Cause_For_Political_reason  CHNAMurder_Cause_Gain  \\\n",
       "Area_Name                                                                 \n",
       "Odisha                                         0                      0   \n",
       "Jharkhand                                      3                      7   \n",
       "Jharkhand                                      3                      7   \n",
       "Bihar                                          0                     47   \n",
       "Karnataka                                      0                      0   \n",
       "\n",
       "           CHNAMurder_Cause_Love_AffairsSexual_Relations  \\\n",
       "Area_Name                                                  \n",
       "Odisha                                                 0   \n",
       "Jharkhand                                              9   \n",
       "Jharkhand                                              9   \n",
       "Bihar                                                 35   \n",
       "Karnataka                                              1   \n",
       "\n",
       "           CHNAMurder_Cause_Lunacy  ...  Murder_Cause_Dowry  \\\n",
       "Area_Name                           ...                       \n",
       "Odisha                           0  ...                 138   \n",
       "Jharkhand                        3  ...                  70   \n",
       "Jharkhand                        3  ...                  70   \n",
       "Bihar                            0  ...                 168   \n",
       "Karnataka                        0  ...                  52   \n",
       "\n",
       "           Murder_Cause_For_Political_reason  Murder_Cause_Gain  \\\n",
       "Area_Name                                                         \n",
       "Odisha                                     4                 60   \n",
       "Jharkhand                                 25                103   \n",
       "Jharkhand                                 25                103   \n",
       "Bihar                                     24                352   \n",
       "Karnataka                                  6                 55   \n",
       "\n",
       "           Murder_Cause_Love_AffairsSexual_Relations  Murder_Cause_Lunacy  \\\n",
       "Area_Name                                                                   \n",
       "Odisha                                            61                    1   \n",
       "Jharkhand                                        158                    3   \n",
       "Jharkhand                                        158                    3   \n",
       "Bihar                                            187                    5   \n",
       "Karnataka                                        130                    0   \n",
       "\n",
       "           Murder_Cause_Other_Causes_or_Motives  \\\n",
       "Area_Name                                         \n",
       "Odisha                                      755   \n",
       "Jharkhand                                   599   \n",
       "Jharkhand                                   599   \n",
       "Bihar                                      1228   \n",
       "Karnataka                                  1093   \n",
       "\n",
       "           Murder_Cause_Personal_Vendetta_or_Enmity  \\\n",
       "Area_Name                                             \n",
       "Odisha                                          113   \n",
       "Jharkhand                                       242   \n",
       "Jharkhand                                       242   \n",
       "Bihar                                           441   \n",
       "Karnataka                                       188   \n",
       "\n",
       "           Murder_Cause_Property_Dispute  Murder_Cause_Total  \\\n",
       "Area_Name                                                      \n",
       "Odisha                                43                1210   \n",
       "Jharkhand                            228                1488   \n",
       "Jharkhand                            228                1488   \n",
       "Bihar                                916                3362   \n",
       "Karnataka                             98                1627   \n",
       "\n",
       "           Murder_Cause_Witchcraft  \n",
       "Area_Name                           \n",
       "Odisha                          28  \n",
       "Jharkhand                       26  \n",
       "Jharkhand                       26  \n",
       "Bihar                            2  \n",
       "Karnataka                        0  \n",
       "\n",
       "[5 rows x 29 columns]"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Generating DataFrame, setting index to the Area Name and replacing NaN values with 0\n",
    "df_motive_data = pd.DataFrame(motive_data)\n",
    "#df_motive_data = df_motive_data.set_index('Area_Name')\n",
    "df_motive_data.fillna(value=0, inplace=True)\n",
    "df_motive_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Area_Name</th>\n",
       "      <th>Year</th>\n",
       "      <th>CHNAMurder_Cause_By_TerroristExtremist</th>\n",
       "      <th>CHNAMurder_Cause_Casteism</th>\n",
       "      <th>CHNAMurder_Cause_Class_Conflict</th>\n",
       "      <th>CHNAMurder_Cause_Communalism</th>\n",
       "      <th>CHNAMurder_Cause_Dowry</th>\n",
       "      <th>CHNAMurder_Cause_For_Political_reason</th>\n",
       "      <th>CHNAMurder_Cause_Gain</th>\n",
       "      <th>CHNAMurder_Cause_Love_AffairsSexual_Relations</th>\n",
       "      <th>...</th>\n",
       "      <th>Murder_Cause_Communalism</th>\n",
       "      <th>Murder_Cause_Dowry</th>\n",
       "      <th>Murder_Cause_For_Political_reason</th>\n",
       "      <th>Murder_Cause_Gain</th>\n",
       "      <th>Murder_Cause_Love_AffairsSexual_Relations</th>\n",
       "      <th>Murder_Cause_Lunacy</th>\n",
       "      <th>Murder_Cause_Other_Causes_or_Motives</th>\n",
       "      <th>Murder_Cause_Personal_Vendetta_or_Enmity</th>\n",
       "      <th>Murder_Cause_Property_Dispute</th>\n",
       "      <th>Murder_Cause_Witchcraft</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Odisha</td>\n",
       "      <td>2007</td>\n",
       "      <td>0</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>138</td>\n",
       "      <td>4</td>\n",
       "      <td>60</td>\n",
       "      <td>61</td>\n",
       "      <td>1</td>\n",
       "      <td>755</td>\n",
       "      <td>113</td>\n",
       "      <td>43</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Jharkhand</td>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>70</td>\n",
       "      <td>25</td>\n",
       "      <td>103</td>\n",
       "      <td>158</td>\n",
       "      <td>3</td>\n",
       "      <td>599</td>\n",
       "      <td>242</td>\n",
       "      <td>228</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Jharkhand</td>\n",
       "      <td>2004</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>70</td>\n",
       "      <td>25</td>\n",
       "      <td>103</td>\n",
       "      <td>158</td>\n",
       "      <td>3</td>\n",
       "      <td>599</td>\n",
       "      <td>242</td>\n",
       "      <td>228</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Bihar</td>\n",
       "      <td>2010</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>11</td>\n",
       "      <td>0</td>\n",
       "      <td>47</td>\n",
       "      <td>35</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>168</td>\n",
       "      <td>24</td>\n",
       "      <td>352</td>\n",
       "      <td>187</td>\n",
       "      <td>5</td>\n",
       "      <td>1228</td>\n",
       "      <td>441</td>\n",
       "      <td>916</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Karnataka</td>\n",
       "      <td>2002</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>4</td>\n",
       "      <td>52</td>\n",
       "      <td>6</td>\n",
       "      <td>55</td>\n",
       "      <td>130</td>\n",
       "      <td>0</td>\n",
       "      <td>1093</td>\n",
       "      <td>188</td>\n",
       "      <td>98</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 28 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   Area_Name  Year  CHNAMurder_Cause_By_TerroristExtremist  \\\n",
       "0     Odisha  2007                                       0   \n",
       "1  Jharkhand  2002                                       0   \n",
       "2  Jharkhand  2004                                       0   \n",
       "3      Bihar  2010                                       0   \n",
       "4  Karnataka  2002                                       0   \n",
       "\n",
       "   CHNAMurder_Cause_Casteism  CHNAMurder_Cause_Class_Conflict  \\\n",
       "0                         11                                0   \n",
       "1                          3                                2   \n",
       "2                          3                                2   \n",
       "3                          2                                2   \n",
       "4                          1                                0   \n",
       "\n",
       "   CHNAMurder_Cause_Communalism  CHNAMurder_Cause_Dowry  \\\n",
       "0                             0                       2   \n",
       "1                             2                      13   \n",
       "2                             2                      13   \n",
       "3                             0                      11   \n",
       "4                             0                       0   \n",
       "\n",
       "   CHNAMurder_Cause_For_Political_reason  CHNAMurder_Cause_Gain  \\\n",
       "0                                      0                      0   \n",
       "1                                      3                      7   \n",
       "2                                      3                      7   \n",
       "3                                      0                     47   \n",
       "4                                      0                      0   \n",
       "\n",
       "   CHNAMurder_Cause_Love_AffairsSexual_Relations  ...  \\\n",
       "0                                              0  ...   \n",
       "1                                              9  ...   \n",
       "2                                              9  ...   \n",
       "3                                             35  ...   \n",
       "4                                              1  ...   \n",
       "\n",
       "   Murder_Cause_Communalism  Murder_Cause_Dowry  \\\n",
       "0                         0                 138   \n",
       "1                         0                  70   \n",
       "2                         0                  70   \n",
       "3                         0                 168   \n",
       "4                         4                  52   \n",
       "\n",
       "   Murder_Cause_For_Political_reason  Murder_Cause_Gain  \\\n",
       "0                                  4                 60   \n",
       "1                                 25                103   \n",
       "2                                 25                103   \n",
       "3                                 24                352   \n",
       "4                                  6                 55   \n",
       "\n",
       "   Murder_Cause_Love_AffairsSexual_Relations  Murder_Cause_Lunacy  \\\n",
       "0                                         61                    1   \n",
       "1                                        158                    3   \n",
       "2                                        158                    3   \n",
       "3                                        187                    5   \n",
       "4                                        130                    0   \n",
       "\n",
       "   Murder_Cause_Other_Causes_or_Motives  \\\n",
       "0                                   755   \n",
       "1                                   599   \n",
       "2                                   599   \n",
       "3                                  1228   \n",
       "4                                  1093   \n",
       "\n",
       "   Murder_Cause_Personal_Vendetta_or_Enmity  Murder_Cause_Property_Dispute  \\\n",
       "0                                       113                             43   \n",
       "1                                       242                            228   \n",
       "2                                       242                            228   \n",
       "3                                       441                            916   \n",
       "4                                       188                             98   \n",
       "\n",
       "   Murder_Cause_Witchcraft  \n",
       "0                       28  \n",
       "1                       26  \n",
       "2                       26  \n",
       "3                        2  \n",
       "4                        0  \n",
       "\n",
       "[5 rows x 28 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Dropping irrelevant Columns\n",
    "df_motive_data=df_motive_data.drop(['CHNAMurder_Cause_Total','Murder_Cause_Total'],1)\n",
    "df_motive_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>type_of_motive</th>\n",
       "      <th>freq</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2010</td>\n",
       "      <td>CHNAMurder_Cause_By_TerroristExtremist</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2008</td>\n",
       "      <td>CHNAMurder_Cause_Class_Conflict</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2002</td>\n",
       "      <td>Murder_Cause_Class_Conflict</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2006</td>\n",
       "      <td>Murder_Cause_By_TerroristExtremist</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2007</td>\n",
       "      <td>CHNAMurder_Cause_Dowry</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Year                          type_of_motive  freq\n",
       "Area_Name                                                                    \n",
       "Andaman & Nicobar Islands  2010  CHNAMurder_Cause_By_TerroristExtremist     0\n",
       "Andaman & Nicobar Islands  2008         CHNAMurder_Cause_Class_Conflict     0\n",
       "Andaman & Nicobar Islands  2002             Murder_Cause_Class_Conflict     4\n",
       "Andaman & Nicobar Islands  2006      Murder_Cause_By_TerroristExtremist     0\n",
       "Andaman & Nicobar Islands  2007                  CHNAMurder_Cause_Dowry     0"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Melting DataFrame into Tidy Format, database-friendly format\n",
    "formatted_df = pd.melt(df_motive_data, id_vars=['Area_Name','Year'], value_vars=['CHNAMurder_Cause_By_TerroristExtremist',\n",
    "'CHNAMurder_Cause_Casteism',\n",
    "'CHNAMurder_Cause_Class_Conflict',\n",
    "'CHNAMurder_Cause_Communalism',\n",
    "'CHNAMurder_Cause_Dowry',\n",
    "'CHNAMurder_Cause_For_Political_reason',\n",
    "'CHNAMurder_Cause_Gain',\n",
    "'CHNAMurder_Cause_Love_AffairsSexual_Relations',\n",
    "'CHNAMurder_Cause_Lunacy',\n",
    "'CHNAMurder_Cause_Other_Causes_or_Motives',\n",
    "'CHNAMurder_Cause_Personal_Vendetta_or_Enmity',\n",
    "'CHNAMurder_Cause_Property_Dispute',\n",
    "'CHNAMurder_Cause_Witchcraft',\n",
    "'Murder_Cause_By_TerroristExtremist',\n",
    "'Murder_Cause_Casteism',\n",
    "'Murder_Cause_Class_Conflict',\n",
    "'Murder_Cause_Communalism',\n",
    "'Murder_Cause_Dowry',\n",
    "'Murder_Cause_For_Political_reason',\n",
    "'Murder_Cause_Gain',\n",
    "'Murder_Cause_Love_AffairsSexual_Relations',\n",
    "'Murder_Cause_Lunacy',\n",
    "'Murder_Cause_Other_Causes_or_Motives',\n",
    "'Murder_Cause_Personal_Vendetta_or_Enmity',\n",
    "'Murder_Cause_Property_Dispute',\n",
    "'Murder_Cause_Witchcraft',\n",
    "],var_name=\"type_of_motive\",value_name=\"freq\")\n",
    "formatted_df = formatted_df.sort_values(by=['Area_Name'])\n",
    "formatted_df = formatted_df.set_index('Area_Name')\n",
    "formatted_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cleaning up Firearm Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>Victims_of_Murder_by_Fire_arms</th>\n",
       "      <th>Victims_of_Murder_by_Licensed_arms</th>\n",
       "      <th>Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Uttar Pradesh</th>\n",
       "      <td>2004</td>\n",
       "      <td>4969</td>\n",
       "      <td>437.0</td>\n",
       "      <td>4532.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Uttar Pradesh</th>\n",
       "      <td>2002</td>\n",
       "      <td>4098</td>\n",
       "      <td>403.0</td>\n",
       "      <td>3695.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Uttar Pradesh</th>\n",
       "      <td>2006</td>\n",
       "      <td>2565</td>\n",
       "      <td>330.0</td>\n",
       "      <td>2235.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Uttar Pradesh</th>\n",
       "      <td>2003</td>\n",
       "      <td>3855</td>\n",
       "      <td>317.0</td>\n",
       "      <td>3538.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Uttar Pradesh</th>\n",
       "      <td>2008</td>\n",
       "      <td>1470</td>\n",
       "      <td>261.0</td>\n",
       "      <td>1209.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Year  Victims_of_Murder_by_Fire_arms  \\\n",
       "Area_Name                                             \n",
       "Uttar Pradesh  2004                            4969   \n",
       "Uttar Pradesh  2002                            4098   \n",
       "Uttar Pradesh  2006                            2565   \n",
       "Uttar Pradesh  2003                            3855   \n",
       "Uttar Pradesh  2008                            1470   \n",
       "\n",
       "               Victims_of_Murder_by_Licensed_arms  \\\n",
       "Area_Name                                           \n",
       "Uttar Pradesh                               437.0   \n",
       "Uttar Pradesh                               403.0   \n",
       "Uttar Pradesh                               330.0   \n",
       "Uttar Pradesh                               317.0   \n",
       "Uttar Pradesh                               261.0   \n",
       "\n",
       "               Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc  \n",
       "Area_Name                                                                            \n",
       "Uttar Pradesh                                             4532.0                     \n",
       "Uttar Pradesh                                             3695.0                     \n",
       "Uttar Pradesh                                             2235.0                     \n",
       "Uttar Pradesh                                             3538.0                     \n",
       "Uttar Pradesh                                             1209.0                     "
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Generating DataFrame, setting index to the Area Name and replacing NaN values with 0\n",
    "df_fire_data = pd.DataFrame(firearms_data)\n",
    "#df_fire_data = df_fire_data.set_index('Area_Name')\n",
    "df_fire_data.fillna(value=0, inplace=True)\n",
    "df_fire_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Area_Name</th>\n",
       "      <th>Year</th>\n",
       "      <th>Victims_of_Murder_by_Licensed_arms</th>\n",
       "      <th>Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>2004</td>\n",
       "      <td>437.0</td>\n",
       "      <td>4532.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>2002</td>\n",
       "      <td>403.0</td>\n",
       "      <td>3695.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>2006</td>\n",
       "      <td>330.0</td>\n",
       "      <td>2235.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>2003</td>\n",
       "      <td>317.0</td>\n",
       "      <td>3538.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Uttar Pradesh</td>\n",
       "      <td>2008</td>\n",
       "      <td>261.0</td>\n",
       "      <td>1209.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Area_Name  Year  Victims_of_Murder_by_Licensed_arms  \\\n",
       "0  Uttar Pradesh  2004                               437.0   \n",
       "1  Uttar Pradesh  2002                               403.0   \n",
       "2  Uttar Pradesh  2006                               330.0   \n",
       "3  Uttar Pradesh  2003                               317.0   \n",
       "4  Uttar Pradesh  2008                               261.0   \n",
       "\n",
       "   Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc  \n",
       "0                                             4532.0                     \n",
       "1                                             3695.0                     \n",
       "2                                             2235.0                     \n",
       "3                                             3538.0                     \n",
       "4                                             1209.0                     "
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Dropping Irrelevant Column\n",
    "df_fire_data=df_fire_data.drop(['Victims_of_Murder_by_Fire_arms'],1)\n",
    "df_fire_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>type_of_arms</th>\n",
       "      <th>freq</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2008</td>\n",
       "      <td>Victims_of_Murder_by_Licensed_arms</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2008</td>\n",
       "      <td>Victims_of_Murder_by_Un_licensedImprovisedCrud...</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2002</td>\n",
       "      <td>Victims_of_Murder_by_Un_licensedImprovisedCrud...</td>\n",
       "      <td>153.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2007</td>\n",
       "      <td>Victims_of_Murder_by_Un_licensedImprovisedCrud...</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2001</td>\n",
       "      <td>Victims_of_Murder_by_Licensed_arms</td>\n",
       "      <td>18.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Year                                       type_of_arms   freq\n",
       "Area_Name                                                                     \n",
       "Andhra Pradesh  2008                 Victims_of_Murder_by_Licensed_arms    3.0\n",
       "Andhra Pradesh  2008  Victims_of_Murder_by_Un_licensedImprovisedCrud...    8.0\n",
       "Andhra Pradesh  2002  Victims_of_Murder_by_Un_licensedImprovisedCrud...  153.0\n",
       "Andhra Pradesh  2007  Victims_of_Murder_by_Un_licensedImprovisedCrud...    6.0\n",
       "Andhra Pradesh  2001                 Victims_of_Murder_by_Licensed_arms   18.0"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Melting DataFrame into Tidy Format, database-friendly format\n",
    "formatted_df = pd.melt(df_fire_data, id_vars=['Area_Name','Year'], value_vars=['Victims_of_Murder_by_Licensed_arms','Victims_of_Murder_by_Un_licensedImprovisedCrudeCountry_made_Arms_Etc'],var_name=\"type_of_arms\",value_name=\"freq\")\n",
    "formatted_df = formatted_df.sort_values(by=['Area_Name'])\n",
    "formatted_df = formatted_df.set_index('Area_Name')\n",
    "formatted_df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cleaning up Victim Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>Group_Name</th>\n",
       "      <th>Victims_Above_50_Yrs</th>\n",
       "      <th>Victims_Upto_10_15_Yrs</th>\n",
       "      <th>Victims_Upto_10_Yrs</th>\n",
       "      <th>Victims_Upto_15_18_Yrs</th>\n",
       "      <th>Victims_Upto_18_30_Yrs</th>\n",
       "      <th>Victims_Upto_30_50_Yrs</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andhra Pradesh</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>67.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>38.0</td>\n",
       "      <td>43.0</td>\n",
       "      <td>269.0</td>\n",
       "      <td>175.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Arunachal Pradesh</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Assam</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>11.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>23.0</td>\n",
       "      <td>45.0</td>\n",
       "      <td>37.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Bihar</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>12.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40.0</td>\n",
       "      <td>191.0</td>\n",
       "      <td>123.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Year               Group_Name  \\\n",
       "Area_Name                                                  \n",
       "Andaman & Nicobar Islands  2001  Murder - Female Victims   \n",
       "Andhra Pradesh             2001  Murder - Female Victims   \n",
       "Arunachal Pradesh          2001  Murder - Female Victims   \n",
       "Assam                      2001  Murder - Female Victims   \n",
       "Bihar                      2001  Murder - Female Victims   \n",
       "\n",
       "                           Victims_Above_50_Yrs  Victims_Upto_10_15_Yrs  \\\n",
       "Area_Name                                                                 \n",
       "Andaman & Nicobar Islands                   0.0                     0.0   \n",
       "Andhra Pradesh                             67.0                    15.0   \n",
       "Arunachal Pradesh                           2.0                     0.0   \n",
       "Assam                                      11.0                     8.0   \n",
       "Bihar                                      12.0                     0.0   \n",
       "\n",
       "                           Victims_Upto_10_Yrs  Victims_Upto_15_18_Yrs  \\\n",
       "Area_Name                                                                \n",
       "Andaman & Nicobar Islands                  0.0                     0.0   \n",
       "Andhra Pradesh                            38.0                    43.0   \n",
       "Arunachal Pradesh                          0.0                     0.0   \n",
       "Assam                                      4.0                    23.0   \n",
       "Bihar                                      0.0                    40.0   \n",
       "\n",
       "                           Victims_Upto_18_30_Yrs  Victims_Upto_30_50_Yrs  \n",
       "Area_Name                                                                  \n",
       "Andaman & Nicobar Islands                     4.0                     2.0  \n",
       "Andhra Pradesh                              269.0                   175.0  \n",
       "Arunachal Pradesh                            10.0                     4.0  \n",
       "Assam                                        45.0                    37.0  \n",
       "Bihar                                       191.0                   123.0  "
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Generating DataFrame, setting index to the Area Name and replacing NaN values with 0\n",
    "# Dropping irrelevant columns\n",
    "df_vic_data = pd.DataFrame(victim_data)\n",
    "#df_vic_data = df_vic_data.set_index('Area_Name')\n",
    "df_vic_data.fillna(0, inplace=True)\n",
    "df_vic_data = df_vic_data.drop(['Victims_Total','Sub_Group_Name'],1)\n",
    "df_vic_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Area_Name</th>\n",
       "      <th>Year</th>\n",
       "      <th>Group_Name</th>\n",
       "      <th>Victims_Above_50_Yrs</th>\n",
       "      <th>Victims_Upto_10_15_Yrs</th>\n",
       "      <th>Victims_Upto_10_Yrs</th>\n",
       "      <th>Victims_Upto_15_18_Yrs</th>\n",
       "      <th>Victims_Upto_18_30_Yrs</th>\n",
       "      <th>Victims_Upto_30_50_Yrs</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Andaman &amp; Nicobar Islands</td>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Andhra Pradesh</td>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>67.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>38.0</td>\n",
       "      <td>43.0</td>\n",
       "      <td>269.0</td>\n",
       "      <td>175.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Arunachal Pradesh</td>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Assam</td>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>11.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>23.0</td>\n",
       "      <td>45.0</td>\n",
       "      <td>37.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Bihar</td>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>12.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40.0</td>\n",
       "      <td>191.0</td>\n",
       "      <td>123.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   Area_Name  Year               Group_Name  \\\n",
       "0  Andaman & Nicobar Islands  2001  Murder - Female Victims   \n",
       "1             Andhra Pradesh  2001  Murder - Female Victims   \n",
       "2          Arunachal Pradesh  2001  Murder - Female Victims   \n",
       "3                      Assam  2001  Murder - Female Victims   \n",
       "4                      Bihar  2001  Murder - Female Victims   \n",
       "\n",
       "   Victims_Above_50_Yrs  Victims_Upto_10_15_Yrs  Victims_Upto_10_Yrs  \\\n",
       "0                   0.0                     0.0                  0.0   \n",
       "1                  67.0                    15.0                 38.0   \n",
       "2                   2.0                     0.0                  0.0   \n",
       "3                  11.0                     8.0                  4.0   \n",
       "4                  12.0                     0.0                  0.0   \n",
       "\n",
       "   Victims_Upto_15_18_Yrs  Victims_Upto_18_30_Yrs  Victims_Upto_30_50_Yrs  \n",
       "0                     0.0                     4.0                     2.0  \n",
       "1                    43.0                   269.0                   175.0  \n",
       "2                     0.0                    10.0                     4.0  \n",
       "3                    23.0                    45.0                    37.0  \n",
       "4                    40.0                   191.0                   123.0  "
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Getting rid of irrelevant Total Victims values\n",
    "df_vic_data_final = df_vic_data[df_vic_data[\"Group_Name\"] != 'Murder - Total Victims']\n",
    "df_vic_data_final.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>Group_Name</th>\n",
       "      <th>Victim_Age_Group</th>\n",
       "      <th>freq</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Area_Name</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2001</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>Victims_Above_50_Yrs</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2009</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>Victims_Upto_18_30_Yrs</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2008</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>Victims_Upto_18_30_Yrs</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2003</td>\n",
       "      <td>Murder - Male Victims</td>\n",
       "      <td>Victims_Above_50_Yrs</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Andaman &amp; Nicobar Islands</th>\n",
       "      <td>2007</td>\n",
       "      <td>Murder - Female Victims</td>\n",
       "      <td>Victims_Upto_18_30_Yrs</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                           Year               Group_Name  \\\n",
       "Area_Name                                                  \n",
       "Andaman & Nicobar Islands  2001  Murder - Female Victims   \n",
       "Andaman & Nicobar Islands  2009  Murder - Female Victims   \n",
       "Andaman & Nicobar Islands  2008  Murder - Female Victims   \n",
       "Andaman & Nicobar Islands  2003    Murder - Male Victims   \n",
       "Andaman & Nicobar Islands  2007  Murder - Female Victims   \n",
       "\n",
       "                                 Victim_Age_Group  freq  \n",
       "Area_Name                                                \n",
       "Andaman & Nicobar Islands    Victims_Above_50_Yrs   0.0  \n",
       "Andaman & Nicobar Islands  Victims_Upto_18_30_Yrs   3.0  \n",
       "Andaman & Nicobar Islands  Victims_Upto_18_30_Yrs   0.0  \n",
       "Andaman & Nicobar Islands    Victims_Above_50_Yrs   1.0  \n",
       "Andaman & Nicobar Islands  Victims_Upto_18_30_Yrs   3.0  "
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Melting DataFrame into Tidy Format, database-friendly format\n",
    "formatted_vic_df = pd.melt(df_vic_data_final, id_vars=['Area_Name','Year','Group_Name'], value_vars=[\"Victims_Above_50_Yrs\",\"Victims_Upto_10_15_Yrs\",\"Victims_Upto_10_Yrs\",\"Victims_Upto_15_18_Yrs\",\"Victims_Upto_18_30_Yrs\",\"Victims_Upto_30_50_Yrs\"],var_name=\"Victim_Age_Group\",value_name=\"freq\")\n",
    "formatted_vic_df = formatted_vic_df.sort_values(by=['Area_Name'])\n",
    "formatted_vic_df = formatted_vic_df.set_index('Area_Name')\n",
    "formatted_vic_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "##### Write output to CSV, UNCOMMENT When needed\n",
    "\n",
    "#clean_air_data.to_csv('Main_Pollution.csv')\n",
    "#formatted_df.to_csv(\"Type_of_Motive.csv\")\n",
    "#formatted_df.to_csv('Murder_By_Firearm.csv')\n",
    "#formatted_vic_df.to_csv('Victim_Age_Gender.csv')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
